FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-root

COPY . .

EXPOSE 8005

CMD ["poetry", "run", "uvicorn", "src.alerte.main:app", "--host", "0.0.0.0", "--port", "8005"]