FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml ./

RUN poetry config virtualenvs.create false && \
    poetry install --no-root --with dev --no-interaction

COPY src/main.py ./main.py
COPY src ./src/
COPY tests ./tests/

ENV PYTHONPATH=/app/src

CMD ["sh", "-c", "poetry run pytest -v --cov=app --cov-report=term-missing --cov-fail-under=80"]